# Generated by Django 4.0 on 2021-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('imagen_cat', models.ImageField(blank=True, upload_to='photos/categorias')),
            ],
        ),
    ]
